global:
    scrape_interval: 30s
    evaluation_interval: 30s
    scrape_timeout: 10s
    external_labels:
        monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['airflow-prometheus:9090']

  - job_name: 'statsd-exporter'
    static_configs:
      - targets: ['airflow-statsd-exporter:9102']

  - job_name: 'prometheus-docker'
    static_configs:
      - targets: [ 'host.docker.internal:9090' ] # Only works on Docker Desktop for Mac

  - job_name: 'docker'
    static_configs:
      - targets: [ 'docker.for.mac.host.internal:9323' ]

    tls_config:
      insecure_skip_verify: true
